The smart_scraper_multi_graph method is too expensive
ScrapeGraphAI/Scrapegraph-ai pull request #756
Opened 2024-10-16 19:40 UTC by shenghongtw

The smart_scraper_multi_graph method uses LLMs to answer questions both in the smart_scraper_graph and at the MergeAnswer node, which leads to higher costs. I created a new method called SmartScraperMultiParseMergeFirstGraph, which only uses LLMs at the MergeAnswer node. This reduces the cost by half for the same use case and achieve similar results, and the execution time is also shortened (as shown in the figure).
![image](https://github.com/user-attachments/assets/64af3f8a-15d5-4141-aa5a-c750a578976c)
![image](https://github.com/user-attachments/assets/ccfd6898-2aa2-4e61-ac05-0e78cf4fe489)
![image](https://github.com/user-attachments/assets/b2faf7cc-219a-4066-a1e5-92ddbf62f816)

2024-10-17 08:09 UTC, VinciGit00 requested changes

2024-10-17 08:09 UTC, VinciGit00 commented on scrapegraphai/graphs/smart_scraper_multi_parse_merge_first_graph.py
Please instead of creating a new graph modify the original one

2024-10-17 16:26 UTC, shenghongtw commented on scrapegraphai/graphs/smart_scraper_multi_parse_merge_first_graph.py
Modify the smart_scraper_multi_graph.py?

2024-10-17 16:26 UTC, shenghongtw commented on scrapegraphai/graphs/smart_scraper_multi_parse_merge_first_graph.py
But original method, called the [raptor](https://ragflow.io/blog/long-context-rag-raptor) method, is useful for deep extraction or in more complex situation.
My idea is to rename the original smart_scraper_multi_graph.py to smart_scraper_multi_raptor_graph.py, and then name my method smart_scraper_multi_graph.py.
What are your thoughts on this?
thx

2024-10-17 17:11 UTC, VinciGit00 commented on scrapegraphai/graphs/smart_scraper_multi_parse_merge_first_graph.py
Ok it looks nice

2024-10-17 17:37 UTC, VinciGit00 commented
please can you add in the examples of openai the configuration?

2024-10-17 17:39 UTC, VinciGit00 commented
and please can you call smart_scraper_multi_lite instead of that?

2024-10-17 17:56 UTC, shenghongtw commented
> and please can you call smart_scraper_multi_lite instead of that?

you mean rename my method name to smart_scraper_multi_lite?

2024-10-17 17:58 UTC, shenghongtw commented
> please can you add in the examples of openai the configuration?

ok

2024-10-17 18:51 UTC, VinciGit00 commented
Yes please rename it

2024-10-17 19:00 UTC, shenghongtw commented
The original smart_scraper_multi_graph keeps its original name?

2024-10-17 19:01 UTC, VinciGit00 commented
> The original smart_scraper_multi_graph keeps its original name?

yes, just change your scraper name, in this way it will be more understandable at the first look

2024-10-17 19:04 UTC, VinciGit00 commented
and please add in examples/openai your script 
<img width="335" alt="Screenshot 2024-10-17 alle 21 03 42" src="https://github.com/user-attachments/assets/b4c8da78-d4b7-4034-b5bb-b05f50ff4ce0">

2024-10-18 07:00 UTC, VinciGit00 commented
Hi @shenghongtw, would you like to create more tests on the test folder please?

2024-10-18 08:12 UTC, shenghongtw commented
> Hi @shenghongtw, would you like to create more tests on the test folder in another pull request please?

No problem.

2024-10-20 08:13 UTC, VinciGit00 commented
Hi @shenghongtw I will merge this pr now, when the tests will be ready I will be glad to merge it also them.
Thank you and have a nice day

2024-10-20 08:13 UTC, merged